### ISSUE TITLE
store size increase out of control when i update react-native version

### ISSUE THREAD

**Issue by jun-hak** [use-global-hook/use-global-hook#84]
'react-native' : 0.63.4 -> 0.66

This is our package.json
"dependencies": {
    "@flat-white/core": "*",
    "@flat-white/models": "*",
    "@flat-white/react-native-sdk": "*",
    "@gorhom/bottom-sheet": "^4",
    "@react-native-async-storage/async-storage": "^1.14.1",
    "@react-native-community/checkbox": "^0.5.7",
    "@react-native-community/datetimepicker": "^3.4.2",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/push-notification-ios": "^1.8.0",
    "@react-native-firebase/analytics": "^11.2.0",
    "@react-native-firebase/app": "^11.4.1",
    "@react-native-firebase/crashlytics": "^11.4.1",
    "@react-navigation/native": "^5.9.8",
    "@react-navigation/stack": "^5.14.9",
    "add": "^2.0.6",
    "dayjs": "^1.10.4",
    "react": "17.0.2",
    "react-native": "0.67.4",
    "react-native-background-timer": "^2.4.1",
    "react-native-ble-plx": "^2.0.2",
    "react-native-dash": "^0.0.11",
    "react-native-disable-battery-optimizations-android": "^1.0.7",
    "react-native-dropdown-picker": "^5.2.3",
    "react-native-fs": "^2.18.0",
    "react-native-gesture-handler": "^2.4.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.3",
    "react-native-mail": "^6.1.0",
    "react-native-modal-datetime-picker": "^9.2.0",
    "react-native-orientation": "^3.1.3",
    "react-native-permissions": "3.3.1",
    "react-native-progress-circle": "^2.1.0",
    "react-native-push-notification": "^5.0.1",
    "react-native-reanimated": "^2.6.0",
    "react-native-responsive-fontsize": "^0.5.0",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^2.18.1",
    "react-native-vector-icons": "^8.1.0",
    "react-native-version-check": "^3.4.2",
    "react-native-webview": "^11.2.5",
    "react-native-zip-archive": "^6.0.3",
    "use-global-hook": "^0.2.1",
    "yarn": "^1.22.10"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "@storybook/react-native": "^5.3.25",
    "@storybook/react-native-server": "^5.3.23",
    "@types/jest": "^27.4.1",
    "@types/react": "^18.0.5",
    "@types/react-native": "^0.67.4",
    "@types/react-native-background-timer": "^2.0.0",
    "@types/react-native-orientation": "^5.0.1",
    "@types/react-test-renderer": "^18.0.0",
    "@types/use-global-hook": "^0.1.3",
    "babel-jest": "^26.6.3",
    "eslint": "^7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.66.2",
    "react-test-renderer": "17.0.2",
    "typescript": "^3.8.3"
  },

The store size increase very fast.
When i use setState, it takes 30 seconds.

is there any issue in react-native 0.66.0 or 0.67.4 ?

In particular, when the store is JSON-formed, "oldState" continues to increase in the "listeners" item.

For example
store => To Json
{
   "state": ...,
   "action": ...
   " listeners": [...] <-- duplicated old state increase, the size is 
}

**Comment by jun-hak** [comment]
And when i upgrade "use-global-hook" version to 0.3.0, i got an error not to find our method? (loadGlobalState)
Am i wrong to use the library?

All code is placed in different files.
`async function loadGlobalState(
  store: Store<iInitialState, iAssociatedActions>,
) { 
..
}
`

`export interface iAssociatedActions {
  loadGlobalState: () => Promise<void>;
}
`
![image](https://user-images.githubusercontent.com/29226480/163954258-69388aa4-d81c-4fab-b424-f2144f957e43.png)


error log:
Possible Unhandled Promise Rejection (id: 2):
TypeError: undefined is not a function
TypeError: undefined is not a function

    at fetchData$ (http://localhost:8081/src\routes.bundle?platform=android&app=com.wellysis.spatchcardio.ex&modulesOnly=true&dev=true&minify=false&runModule=true&shallow=true:396:78)


Oh... I look the example again, and i remove React in globalhook
![image](https://user-images.githubusercontent.com/29226480/163957557-cdba37e4-3437-42b5-9111-804a03f10527.png)

Typescript makes many errors, however, build success. Thank you.

I think I've become more stupid because I'm so dependent on tools.
